"""Generators (manage-docs v2 sections 2, 6 check 4, 8.2 "generators LAST").

Built in:
- `docs-map` -> docs/README.md: every live doc, one line: title, owner area, receipt status. It
  prints only STORED values (`verified.at` or "unverified"), never computed age or drift, so
  `generate --check` does not change day to day with no repo change (eng-review P2).
- `work-index` -> work/README.md: every record with kind, date and status (private repos only;
  in a public repo work/ is local-only).

docs.json `generators` entries:
- `{"id", "output", "cmd": [argv]}`: docs.py runs cmd at the repo root, takes stdout as the
  content and writes it under a generated header (markdown and html outputs).
- `{"id", "cmd": [argv], "check": [argv]}`: an external generator that writes its own files
  (uplink's agent-docs router); `generate` runs cmd, `generate --check` runs check.

A generated file starts with `<!-- manage-docs:generated id=<id> hash=<sha256 of the rest> -->`.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from docslib import config, frontmatter, receipts

MAP = "docs/README.md"
WORK_INDEX = "work/README.md"
HEADER_EXT = (".md", ".mdx", ".html")
KIND_DIRS = {"handoffs": "handoff", "runs": "run", "evidence": "evidence", "audits": "audit"}
REC_NAME = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+?)(\.md)?$")


class GenerateError(Exception):
    pass


def _tracked(root: Path) -> List[str]:
    out = subprocess.run(["git", "ls-files", "-z"], cwd=root, capture_output=True, check=True).stdout
    return sorted(p for p in out.decode("utf-8", "surrogateescape").split("\0") if p)


def _files(root: Path, under: str) -> List[str]:
    """Tracked files plus untracked files under `under` (public repos keep work/ untracked)."""
    paths = set(_tracked(root))
    base = Path(root) / under
    if base.is_dir():
        for fp in base.rglob("*"):
            if fp.is_file():
                paths.add(fp.relative_to(root).as_posix())
    return sorted(p for p in paths if p.startswith(under))


def _title(text: str, fm: Optional[dict], path: str) -> str:
    if fm and fm.get("title"):
        return str(fm["title"])
    for ln in frontmatter.body(text).splitlines():
        m = re.match(r"^#\s+(.*)", ln)
        if m:
            return m.group(1).strip()
    return Path(path).stem


def docs_map(root: Path, cfg: dict) -> str:
    root = Path(root)
    rows: Dict[str, List[str]] = {}
    for p in _tracked(root):
        if not p.startswith("docs/") or p == MAP or not config.is_doc(cfg, p):
            continue
        if config.is_public(cfg) and config.local_only(p):
            continue
        if not (root / p).is_file():
            continue  # still in the index but already moved away in the working tree (migration apply)
        text = (root / p).read_text(encoding="utf-8", errors="replace")
        try:
            fm, _ = frontmatter.parse(text)
        except frontmatter.FrontmatterError:
            fm = None
        area = p.split("/")[1] if p.count("/") >= 2 else "docs"
        if receipts.is_generated(text):
            status = "generated"
        elif fm and fm.get("verified"):
            status = f"verified {fm['verified']['at']}"
        elif config.frontmatter_required(cfg, p):
            status = "unverified"
        else:
            status = "-"
        owner = (fm or {}).get("owner", "-")
        rel = p[len("docs/"):]
        rows.setdefault(area, []).append(f"- [{_title(text, fm, p)}]({rel}) | owner: {owner} | {status}")
    out = ["# Docs map", "",
           "Every doc in this repo, one line each: title, owner area, receipt status. Generated by",
           "`python3 tools/docs/docs.py generate`; never edit by hand.", ""]
    if not config.is_public(cfg):
        tracked = set(_tracked(root))
        # work/README.md is always generated in a private repo, so this pointer always resolves
        out.append("Records (handoffs, runs, evidence, audits) live in [work/](../work/README.md).")
        if any(p.startswith("docs/roadmap/") for p in tracked) or (Path(root) / "docs/roadmap/ROADMAP.md").is_file():
            out.append("Roadmap and decisions: [docs/roadmap/](roadmap/).")
        out.append("")
    for area in sorted(rows):
        out += [f"## {area}", ""] + sorted(rows[area]) + [""]
    return "\n".join(out).rstrip("\n") + "\n"


def record_status(root: Path, path: str) -> str:
    """open|done for a record path (folder records read record.json)."""
    root = Path(root)
    parts = path.split("/")
    if path.startswith("work/archive/"):
        return "done"
    if len(parts) > 3:
        rj = root / "/".join(parts[:3]) / "record.json"
        if rj.is_file():
            try:
                return json.loads(rj.read_text(encoding="utf-8")).get("status", "open")
            except json.JSONDecodeError:
                return "open"
        return "done"
    try:
        fm, _ = frontmatter.parse((root / path).read_text(encoding="utf-8", errors="replace"))
    except (frontmatter.FrontmatterError, OSError):
        return "open"
    if fm is None:
        return "done"
    return str(fm.get("status", "open"))


def records(root: Path) -> List[Tuple[str, str, str, str]]:
    """[(kind, date, record path, status)]: one per dated record (file or folder) under work/."""
    seen = {}
    for p in _files(root, "work/"):
        parts = p.split("/")
        if len(parts) < 3 or parts[1] == "archive" or p == WORK_INDEX:
            continue
        kind = KIND_DIRS.get(parts[1], parts[1])
        m = REC_NAME.match(parts[2])
        if not m:
            continue
        rec = "/".join(parts[:3])
        if rec not in seen:
            seen[rec] = (kind, m.group(1), rec, record_status(root, p))
    return sorted(seen.values(), key=lambda r: (r[1], r[2]), reverse=True)


def work_index(root: Path, cfg: dict) -> str:
    out = ["# Work records", "",
           "Handoffs, runs, evidence and audits, newest first. Generated by",
           "`python3 tools/docs/docs.py generate`; never edit by hand. Swept records live in",
           "`work/archive/<year>/<kind>/`.", ""]
    recs = records(root)
    if not recs:
        out.append("No records yet.")
    for kind, date, rec, status in recs:
        rel = rec[len("work/"):]
        out.append(f"- {date} {kind}: [{rel}]({rel}) ({status})")
    return "\n".join(out).rstrip("\n") + "\n"


def wrap(gen_id: str, content: str, path: str) -> str:
    if path.endswith(HEADER_EXT):
        return receipts.generated_header(gen_id, content) + content
    return content


def unwrap(text: str) -> str:
    first, _, rest = text.partition("\n")
    return rest if receipts.GENERATED_RX.search(first) else text


def builtin(cfg: dict) -> List[dict]:
    gens = [{"id": "docs-map", "output": MAP, "builtin": docs_map}]
    if not config.is_public(cfg):
        gens.append({"id": "work-index", "output": WORK_INDEX, "builtin": work_index})
    return gens


def all_generators(cfg: dict) -> List[dict]:
    return builtin(cfg) + [dict(g) for g in cfg.get("generators") or []]


def render(root: Path, cfg: dict, gen: dict) -> str:
    if "builtin" in gen:
        return gen["builtin"](root, cfg)
    p = subprocess.run(gen["cmd"], cwd=root, capture_output=True, text=True)
    if p.returncode != 0:
        raise GenerateError(f"generator {gen['id']} failed ({p.returncode}): {p.stderr.strip()[:400]}")
    return p.stdout


def run(root: Path, cfg: dict, check: bool = False, builtin_only: bool = False) -> Tuple[int, List[str]]:
    """Run every generator. check=True: 1 when any output differs (nothing written).

    Returns (exit code, [changed output paths, or `<id>` for external generators])."""
    root = Path(root)
    changed: List[str] = []
    for gen in (builtin(cfg) if builtin_only else all_generators(cfg)):
        if "output" not in gen:
            cmd = gen["check"] if check else gen["cmd"]
            p = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
            if p.returncode != 0:
                if check:
                    changed.append(gen["id"])
                    continue
                raise GenerateError(f"generator {gen['id']} failed ({p.returncode}): {p.stderr.strip()[:400]}")
            continue
        content = render(root, cfg, gen)
        want = wrap(gen["id"], content, gen["output"])
        fp = root / gen["output"]
        have = fp.read_text(encoding="utf-8") if fp.is_file() else None
        if have == want:
            continue
        changed.append(gen["output"])
        if not check:
            fp.parent.mkdir(parents=True, exist_ok=True)
            fp.write_text(want, encoding="utf-8")
    return (1 if (check and changed) else 0), changed


def fingerprints(root: Path, cfg: dict, outputs: List[str]) -> List[dict]:
    """ER18: generator changes are fingerprinted by generator id + output hash."""
    out = []
    for gen in all_generators(cfg):
        if gen.get("output") in outputs:
            text = (Path(root) / gen["output"]).read_text(encoding="utf-8")
            out.append({"op": "generate", "path": gen["output"], "input": f"{gen['id']}:{receipts.sha256_text(text)}"})
    return out
